analyzers:
    asmdecl:
    assign:
    atomic:
    bools:
    buildtag:
    cgocall:
    composites:
    copylocks:
    errorsas:
    framepointer:
    httpresponse:
    ifaceassert:
    loopclosure:
    lostcancel:
    nilfunc:
    nilness:
    printf:
    shift:
    sigchanyzer:
    stdmethods:
    stringintconv:
    structtag:
    testinggoroutine:
    tests:
    timeformat:
    unmarshal:
    unreachable:
    unsafeptr:
    unusedresult:
test: true
