name: "Code Analysis"

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 0 * * 0"

concurrency:
  group: ${{ format('{0}-{1}-{2}', github.workflow, github.head_ref, github.ref_name) }}
  cancel-in-progress: true

jobs:
  CodeQL:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: go

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  Checks:
    strategy:
      matrix:
        go:
          - "1.18"
          - "1.19"
          - "1.20"
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: go fmt
        run: |
          make fmt
          DELTA="$(git diff --numstat)"
          if [ -n "${DELTA}" ]
          then
            echo "${DELTA}"
            git diff
            exit 1
          fi
      - name: go vet
        run: make github-vet
      - name: generate config
        run: |
          make generate-config
          DELTA="$(git diff --numstat)"
          if [ -n "${DELTA}" ]
          then
            echo "${DELTA}"
            git diff
            exit 1
          fi

  tested:
    runs-on: ubuntu-latest
    needs: [CodeQL, Checks]
    if: always()
    steps:
      - name: All tests ok
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Some tests failed
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
