name: gochecker

on:
  workflow_call:
    inputs:
      config:
        required: true
        type: string
      version:
        type: string
        default: latest
      args:
        type: string
      go-version:
        type: string
        default: ""

jobs:
  gochecker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ inputs.go-version }}
      - name: Install gochecker
        run: go install github.com/sv-tools/gochecker@${{ inputs.version }}
      - name: gochecker
        run: $(go env GOPATH)/bin/gochecker -config ${{ inputs.config }} -output github ${{ inputs.args }} ./...
